apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-app
  namespace: dict-client-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app
    spec:
      containers:
      - name: java-app-container
        image: predanerd/dict_client:1
        resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "200m"
        ports:
        - containerPort: 8080
        command: ["java", "-jar", "/app/client.jar", "-s", "localhost","-p","8080"]
        
