apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-app
  namespace: dict-server-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app
    spec:
      containers:
      - name: java-app-container
        image: predanerd/dict_server:1
        resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "200m"
        ports:
        - containerPort: 8080
        command: ["java", "-jar", "/app/server.jar", "-f", "/app/dict.txt","-p","8080"]
        
